services:
    backend:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        environment:
            DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        env_file: .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
